# NLP

In [5]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv("IMDB Dataset.csv")

In [12]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [15]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

# Step-1 Lowercasing

In [17]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# Whole Column in Lowercase

In [21]:
df['review'] = df['review'].str.lower()

In [23]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Step-2 Removing HTML Tags

In [27]:
import re
def remove_html_tag(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r"" ,text)

In [29]:
text = "<html><body> sddsdsffvfvsd <p> <p>"

In [31]:
remove_html_tag(text)

' sddsdsffvfvsd  '

In [33]:
df['review'] = df['review'].apply(remove_html_tag)

In [35]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Step-3 remove URL

In [40]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'' , text)

In [42]:
text2 = "For Notebook go to https://www.github.com/Amaan-Syed-2182"

In [44]:
remove_url(text2)

'For Notebook go to '

# Step-4 Remove Punctuation

In [60]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [62]:
exclude = string. punctuation

In [64]:
def remove_punc(text):
    for char in exclude:
        text = text.replace (char , '')
    return text

In [66]:

text1 = 'string. With. Punctuation?'

remove_punc(text1)

'string With Punctuation'

In [69]:
df['review'] = df['review'].apply(remove_punc)

In [71]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Step-5 Chatword Treatment

In [77]:
chat_words = {'u2' : 'you too' , 'BBL': 'Be Back Later' , 'GAL': 'Get A Life'}

chat_words

{'u2': 'you too', 'BBL': 'Be Back Later', 'GAL': 'Get A Life'}

{'u2': 'you too', 'BBL': 'Be Back Later', 'GAL': 'Get A Life'}

In [79]:
def chat_conversation(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words :
            new_text.append(chat_words[w.upper()])
        else :
            new_text.append(w)

    return "".join(new_text)

In [81]:

chat_conversation('BBL')

'Be Back Later'